from tvshowinformation import *

tvshow = showInformation(input('What show would you like to view the information of? '))
print('The ID Number of this show is: ' + str(tvshow.getIdShowInfo()))
print('The main cast of the show is: ' + str(tvshow.getCast()))
print('The genres of the show are: ' + str(tvshow.getGenres()))
print('The rating  of the show: '+str(tvshow.getShowRating()))
print('The total runtime of the show is: ' + str(tvshow.getTotalRuntime()))
print('The number of episodes in this show are: ' + str(tvshow.getEpisodesTotal()))
print('The summary of the show is: ' + str(tvshow.getShowSummary()))
print('------')
print('The number of seasons in this show is: ' + str(tvshow.getSeasons()))
print('The number of episodes in Season 1 are: ' + str(tvshow.getEpisodesInSeason(1)))
print('The number of episodes in Season 2 are: ' + str(tvshow.getEpisodesInSeason(2)))
print('The number of episodes in Season 3 are: ' + str(tvshow.getEpisodesInSeason(3)))
print('The number of episodes in Season 10 are: ' + str(tvshow.getEpisodesInSeason(10)))
print('The number of episodes in Season 20 are: ' + str(tvshow.getEpisodesInSeason(20)))
print('------')
print('The name of the first episode in season 1 of the show show is: ' + str(tvshow.getEpisodeName(1, 1)))
print('The runtime of season 1, episode one is: ' + str(tvshow.getEpisodeRuntime(1, 1)))
print('The description of Season 1, Episode 1 is: ' + str(tvshow.getEpisodeDescription(1, 1)))
print('------')
print('The name of the second episode in season 1 of the show is: ' + str(tvshow.getEpisodeName(1, 2)))
print('The runtime of season 1, episode two is: ' + str(tvshow.getEpisodeRuntime(1, 2)))
print('The description of Season 1, Episode 2 is: ' + str(tvshow.getEpisodeDescription(1, 2)))
print('------')
print('The name of the first episode in season 10 of the show is: ' + str(tvshow.getEpisodeName(10, 1)))
print('The runtime of season 10, episode one is: ' + str(tvshow.getEpisodeRuntime(10, 1)))
print('The description of Season 10, Episode 1 is: ' + str(tvshow.getEpisodeDescription(10, 1)))
print('------')
print('The name of the second episode in season 10 of the show is: ' + str(tvshow.getEpisodeName(10, 2)))
print('The runtime of season 10, episode two is: ' + str(tvshow.getEpisodeRuntime(10, 2)))
print('The description of Season 10, Episode 2 is: ' + str(tvshow.getEpisodeDescription(10, 2)))
print('')


